version: "3.8"

services:
  http_sse:
    container_name: "http_sse"
    build:
      context: "."
      dockerfile: "./Dockerfile"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    container_name: "postgres"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "sse"
      POSTGRES_PORT: "5423"
    ports:
      - "5423:5432"
    volumes:
      - ./storage/postgres/dbs_schema.sql:/docker-entrypoint-initdb.d/database.sql